name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove existing Docker image
        run: |
          docker rmi stanislav1502/forum-bk:latest || true

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: stanislav1502/forum-bk:latest
          context: .
          file: ./Dockerfile

      - name: Log out of Docker Hub
        if: always()
        run: docker logout
